# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Thiacoules Professional Website"
description:	       "A minimalist website deigned for professional purposes"
editor:              "Ian Thiacoules"

# RSS 2.0 can be used instead of Atom by uncommenting the following two lines
#feed:
#  path: rss-feed.xml
