# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'About',  url: 'about'}
- {name: 'Publications', url: 'publications'}
- {name: 'Research',       url: 'research'}
- {name: 'Code/Data',      url: 'code/data'}
- {name: 'Languages',              url: 'languages'}
- {name: 'CV',              url: 'cv'}
- {name: 'Press',              url: 'press'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/astrothiacoules'}
- {icon: 'linkedin', link:   'https://www.linkedin.com/'}
- {icon: 'instagram', link:  'https://instagram.com/thiacoules'}
- {icon: 'email', link:   'mailto:thiacoules@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Check out ...'

post_date_prefix: 'Written on'
